"""Adicionar valor adicional por mes em parcelas

Revision ID: 6aac1aa367cd
Revises: b5ed7b61917d
Create Date: 2026-03-02 20:15:36.677788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac1aa367cd'
down_revision = 'b5ed7b61917d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_per_month', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_column('additional_per_month')

    # ### end Alembic commands ###
