"""Adicionar tabelas orcamento, metas, contribuicoes, parcelas e colunas de parcela em despesas

Revision ID: b5ed7b61917d
Revises: 7b5943fe7c8b
Create Date: 2026-03-02 19:30:10.882460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ed7b61917d'
down_revision = '7b5943fe7c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_goals_user_id'), ['user_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'month', 'year', name='uq_budget_user_cat_month_year')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('num_installments', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payee', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installments_user_id'), ['user_id'], unique=False)

    op.create_table('savings_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_contributions_goal_id'), ['goal_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_installment_id', 'installments', ['installment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_installment_id', type_='foreignkey')
        batch_op.drop_column('installment_number')
        batch_op.drop_column('installment_id')

    with op.batch_alter_table('savings_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_contributions_goal_id'))

    op.drop_table('savings_contributions')
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installments_user_id'))

    op.drop_table('installments')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_goals_user_id'))

    op.drop_table('savings_goals')
    # ### end Alembic commands ###
